Отрисуй меня полностью (часть 2)
htmlacademy-javascript/2140577-kekstagram-26 pull request #11
Opened 2022-07-18 12:01 UTC by TatianaKhoroshilova

---
:mortar_board: [Отрисуй меня полностью (часть 2)](https://up.htmlacademy.ru/javascript/26/user/2140577/tasks/13)

2022-07-18 17:59 UTC, syutkinadasha requested changes
прокомментировала в личных сообщениях

2022-07-20 09:01 UTC, syutkinadasha requested changes
все обсудили в лс

2022-07-20 16:54 UTC, syutkinadasha requested changes
обсудим ошибки на консультации

2022-07-21 20:45 UTC, syutkinadasha requested changes

2022-07-21 20:45 UTC, syutkinadasha commented on js/fullPhoto.js
> +  if(comments, avatar, name) {
что ты этим хочешь сказать? я так понимаю, ты смотришь, существуют ли comments, avatar и name одновременно? запись неправильная тогда, надо так comments && avatar && name - хотя вот вообще не вижу смысла в этом сейчас, я же тебе для примера писала, можешь это условие вообще убрать

2022-07-21 20:57 UTC, TatianaKhoroshilova commented on js/fullPhoto.js
> +  if(comments, avatar, name) {
Я хотела добавить имена и аватар, если есть коммент
В задании кроме коммента еще увидела аватар и имя, поэтому их добавила.

"Список комментариев под фотографией: комментарии должны вставляться в блок .social__comments. Разметка каждого комментария должна выглядеть так:

<li class="social__comment">
    <img
        class="social__picture"
        src="{{аватар}}"
        alt="{{имя комментатора}}"
        width="35" height="35">
    <p class="social__text">{{текст комментария}}</p>
</li>"

убрать аватар с именем? или исправить на comments && avatar && name

2022-07-22 06:55 UTC, syutkinadasha approved these changes

2022-07-22 06:55 UTC, merged