функции и main js
htmlacademy-javascript/2140577-kekstagram-26 pull request #2
Opened 2022-06-20 12:30 UTC by TatianaKhoroshilova

2022-06-20 18:42 UTC, syutkinadasha requested changes
рекомендую запускать свой код перед отправкой на проверку, у тебя бы все эти ошибки показало в консоли

2022-06-20 18:42 UTC, syutkinadasha commented on js/main.js
> +  max = Math.floor(max);
а где let или const перед определением переменных?

2022-06-20 18:42 UTC, syutkinadasha commented on js/main.js
> +let commentLength = comment.length
это что за фигня?

2022-06-20 18:42 UTC, syutkinadasha commented on js/main.js
> +};
вот эта функция нерабочая. Проблемы с фигурными скобками тут

2022-06-21 15:48 UTC, TatianaKhoroshilova commented on js/main.js
> +};
спасибо, исправила)

2022-06-21 15:48 UTC, TatianaKhoroshilova commented on js/main.js
> +let commentLength = comment.length
удалила;
хотела считать количество символов в строке 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/length

2022-06-21 15:53 UTC, syutkinadasha requested changes

2022-06-21 15:53 UTC, syutkinadasha commented on js/main.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
а почему ты не используешь minNumber, maxNumber в этой строке? а используешь исходные значения min и max?

2022-06-21 16:12 UTC, TatianaKhoroshilova commented on js/main.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
пропустила, в консоли случайные значения выпадали

2022-06-21 18:55 UTC, syutkinadasha approved these changes

2022-06-21 18:55 UTC, merged