Больше деталей
htmlacademy-javascript/2140577-kekstagram-26 pull request #3
Opened 2022-06-29 19:49 UTC by TatianaKhoroshilova

---
:mortar_board: [Больше деталей](https://up.htmlacademy.ru/javascript/26/user/2140577/tasks/9)

2022-06-29 20:52 UTC, syutkinadasha requested changes

2022-06-29 20:52 UTC, syutkinadasha commented on js/main.js
> +getRandomIntInclusive ();
зачем ты эту функцию тут вызываешь? у тебя консоль не ругается, что ты без аргументов это делаешь?

2022-06-29 20:52 UTC, syutkinadasha commented on js/main.js
> +checkCommentLength ();
здесь аналогично, вызываешь без аргументов зачем-то

2022-06-29 20:52 UTC, syutkinadasha commented on js/main.js
> +const ID = getIdList(25);
не очень правильно константу называть в верхнем регистре, когда она является результатом выполнения функции или функцией. Я бы здесь и дальше рекомендовала бы переименовать их (кроме description, message, names - тут все верно названо)

2022-06-29 20:52 UTC, syutkinadasha commented on js/main.js
> +  getPhotoDescription()
это можно в одну строку записать

2022-06-29 20:52 UTC, syutkinadasha commented on js/main.js
> +}
сделай тут, чтоб все красиво было оформлено
1. открывающие фигурные скобки на строке с условием, 
2. закрывающие фигурные скобки на отдельной строке, 
3. все, что внутри фигурных скобок должно быть с отступом

2022-06-29 20:52 UTC, syutkinadasha commented on js/main.js
> +};
1. Если ты используешь синтаксис стрелочной функции, не забывай, что когда ты внутри функции выполняешь только return, то можно его не писать. В данном случае функция будет выглядеть примерно так const testFunc = () => ({ твой объект }). Т.е. если ты возвращаешь объект или массив, то его нужно взять в круглые скобки.
2. Мне не очень нравится такое использование ID[getRandomIntInclusive (0, ID.length+1)], в объекте выглядит как костыль. Давай лучше напишем для этого отдельную функцию, назовем ее например так getRandomArrayElement(arr). В нее будем передавать один из массивов (ID, AVATAR, MESSAGE или NAMES) и будем возвращать arr[getRandomIntInclusive (0, arr.length+1)]. Это как пример, можешь что-то свое сделать

2022-06-30 15:29 UTC, TatianaKhoroshilova commented on js/main.js
> +const ID = getIdList(25);
исправила на нижний регистр

2022-06-30 15:29 UTC, TatianaKhoroshilova commented on js/main.js
> +getRandomIntInclusive ();
удалила, не знаю, зачем оставила.

2022-06-30 15:33 UTC, TatianaKhoroshilova commented on js/main.js
> +  getPhotoDescription()
удалила этот console.log, если я не ошибаюсь,он не нужен в задании. Эти данные и так выводятся в массиве из 25 объектов

2022-06-30 15:33 UTC, TatianaKhoroshilova commented on js/main.js
> +}
исправила, спасибо

2022-06-30 15:33 UTC, TatianaKhoroshilova commented on js/main.js
> +};
добавила функцию

2022-07-02 07:00 UTC, syutkinadasha approved these changes

2022-07-04 15:39 UTC, syutkinadasha approved these changes

2022-07-04 15:44 UTC, merged